development:
  adapter: postgresql
  encoding: utf8
  database: bitly_development
  pool: 5
  username: postgres
  password: postgres

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: bitly_test
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: utf8
  database: bitly_production
  pool: 5
  username: postgres
  password: postgres
